<?php

$query->insert('intakes', [
	'first_name' => $_POST['first_name'],
	'last_name' => $_POST['last_name'],
	'date_of_birth' => $_POST['date_of_birth'],
	'records_number' => $_POST['records_number'],
	'diagnosis' => $_POST['diagnosis'],
	'service' => $_POST['service'],
	'q_1' => $_POST['q_1'],
	'q_2' => $_POST['q_2'],
	'q_3' => $_POST['q_3'],
	'q_4' => $_POST['q_4'],
	'q_5' => $_POST['q_5'],
	'q_6' => $_POST['q_6'],
	'q_7' => $_POST['q_7'],
	'q_8' => $_POST['q_8'],
	'q_9' => $_POST['q_9'],
	'q_9_more' => $_POST['q_9_more'],
	'q_10' => $_POST['q_10'],
	'q_11' => $_POST['q_11'],
	'q_12' => $_POST['q_12'],
	'q_12_more' => $_POST['q_12_more'],
	'q_13' => $_POST['q_13'],
	'q_14' => $_POST['q_14'],
	'q_15' => $_POST['q_15'],
	'q_16' => $_POST['q_16'],
	'q_17' => $_POST['q_17'],
	'q_18' => $_POST['q_18'],
	'q_19' => $_POST['q_19'],
	'q_20' => $_POST['q_20'],
	'q_21' => $_POST['q_21'],
	'q_22' => $_POST['q_22'],
	'q_23' => $_POST['q_23'],
	'q_24' => $_POST['q_24'],
	'therapist_comments' => $_POST['therapist_comments'],
	'therapist_name' => $_POST['therapist_name'],
	'entered_date' => $_POST['entered_date'],
]);